### ISSUE TITLE
.parser缺失

### ISSUE THREAD

**Issue by satori2017** [YBRua/SrcMarker#2]
在metrics/syntax_match.py中第九行from .parser import ...无法导入.parser

**Comment by YBRua** [comment]
Hi，感谢指正，这个问题似乎是 .gitignore 里的 "parser/" 把 "metrics/parser" 目录一并 ignore 掉导致的。

我 push 了一版更新的代码，麻烦你再试一下？

**Comment by satori2017** [comment]
已解决问题
