### ISSUE TITLE
synatax_match.py 有关地址拼接的问题

### ISSUE THREAD

**Issue by BHunterB** [YBRua/SrcMarker#3]
"./metrics/syntax_match.py", line 78

JAVA_LANGUAGE = Language(root_dir + "../parser/languages.so", lang)

我在运行的时候出现了xxx/metrics../parser/languages.so 这样有问题的地址。os报错cannot open shared object file: No such file or directory

将其改为

JAVA_LANGUAGE = Language(root_dir + "/../parser/languages.so", lang)

可解决。不过感觉最好还是用os.path.join?

**Comment by YBRua** [comment]
确实用 `os.path.join` 更好，对应位置的代码已经更新。

感谢指正！
